export const prerender = false;
import type { APIRoute } from 'astro';
import { z } from 'zod';
import { assertAllowedOrigin } from '@/lib/server/origin-guard';
import { privateApiNoStore } from '@/lib/server/cache-control';
import { parseBody, withErrorHandling } from '@/lib/utils/handlers';
import { HttpError, jsonResponse } from '@/lib/utils/http';
import { requirePlatformAdmin } from '@/lib/server/community-permissions';
import { adminAdjustTokens, getOrCreateTokenBalance } from '@/server/services/race-token.service';
import { prisma } from '@/lib/db/prisma';
const schema=z.object({amount:z.number().int().refine((n)=>n!==0),reason:z.string().min(5).max(240)});
export const PATCH: APIRoute=(context)=>withErrorHandling(async()=>{assertAllowedOrigin(context.request);const admin=await requirePlatformAdmin(context);const id=context.params.id;if(!id)throw new HttpError(400,'User ID required.');const body=await parseBody(context.request,schema);await adminAdjustTokens(id,body.amount,body.reason,admin.id);const balance=await getOrCreateTokenBalance(id);const ledger=await prisma.raceTokenLedger.findMany({where:{userId:id},orderBy:{createdAt:'desc'},take:8});const res=jsonResponse(200,{balance,ledger});res.headers.set('Cache-Control',privateApiNoStore);return res;});
